version: "3"
services:
  pgsql:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_store:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=VKyXzuCgM2yr
    networks:
      - local_net 

volumes:
  pg_store:
    external: true
networks:
  local_net:
    external: true
