version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.2.0
    container_name: es701
    environment:
      - cluster.name=es7-cluster
      - node.name=es701
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es701
      - cluster.initial_master_nodes=es701,es702
    ports:
      - "9200:9200"
    volumes:
      - es7_store:/usr/share/elasticsearch/data
      - "./jvm.options:/usr/share/elasticsearch/config/jvm.options"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - local_net

  elasticsearch2:
    image: elasticsearch:7.2.0
    container_name: es702
    environment:
      - cluster.name=es7-cluster
      - node.name=es702
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es701
      - cluster.initial_master_nodes=es701,es702
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es7_store2:/usr/share/elasticsearch/data
    networks:
      - local_net

  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://es701:9200
    networks:
      - local_net
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.2.0
    container_name: kibana7
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - local_net
    depends_on:
      - elasticsearch

volumes:
  es7_store:
    external: true
  es7_store2:
    external: true

networks:
  local_net:
    external: true
