version: "3"
services:
  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://es701:9200
      - LOG_LEVEL=debug
    ports:
      - "14269"
      - "14268:14268"
      - "14250"
      - "9411:9411"
    restart: on-failure
    networks:
      - local_net
    command:
      [
        "--es.num-shards=1",
        "--es.num-replicas=0",
        "--collector.zipkin.host-port=:9411",
        "--log-level=debug",
      ]
  jaeger-agent:
    image: jaegertracing/jaeger-agent:latest
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://es701:9200
      - LOG_LEVEL=debug
    command:
      [
        "--reporter.grpc.host-port=jaeger-collector:14250",
        "--reporter.grpc.retry.max=1000",
      ]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    depends_on:
      - jaeger-collector
    networks:
      - local_net

  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://es701:9200
      - LOG_LEVEL=debug
      - JAEGER_AGENT_HOST=jaeger-agent
      - JAEGER_AGENT_PORT=6831
    ports:
      - "16686:16686"
      - "16687:16687"
    restart: on-failure
    networks:
      - local_net
    command: ["--es.num-shards=1", "--es.num-replicas=0"]
    depends_on:
      - jaeger-agent

networks:
  local_net:
    external: true
