version: "3"
services:
  mysql:
    image: rabbitmq:management
    restart: unless-stopped
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - local_net 
networks:
  local_net:
    external: true
