version: "3"
services:
  elasticsearch:
    image: elasticsearch:6.4.2
    container_name: db_elasticsearch
    restart: always
    ports:
      - "9200:9200"
    volumes:
      - es6_store:/usr/share/elasticsearch/data
      - "./jvm.options://usr/share/elasticsearch/config/jvm.options"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - local_net
volumes:
  es6_store:
    external: true
networks:
  local_net:
    external: true
