version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd 
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - local_net
    hostname: nsqlookupd
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=0.0.0.0 
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
    hostname: nsqd
    networks:
      - local_net
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161 
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"
    hostname: nsqadmin
    networks:
      - local_net 

networks:
  local_net:
    driver: bridge
