version: "3"
services:
  mysql:
    image: mysql:5.6
    restart: unless-stopped
    container_name: db_mysql56
    ports:
      - "13306:3306"
    volumes:
      - ./conf/my56.cnf:/etc/mysql/conf.d
      - mysql_store56:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - local_net 
volumes:
  mysql_store56:
    external: true
networks:
  local_net:
    external: true
