version: "3.5"
services:
  mysql:
    image: mysql:5.7.23
    ports:
      - "3307:3306"
    volumes:
      - mysql_store:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    deploy:
      replicas: 1
    networks:
      legacy:
        aliases:
          - mysql
        ipv4_address: 10.0.6.4

volumes:
  mysql_store:
    external: true
networks:
  legacy:
    driver: overlay
    ipam:
      driver: default
      config:
      -
        subnet: 10.0.6.0/24
