version: "3"
services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: db_mysql8
    ports:
      - "3306:3306"
    volumes:
      - mysql_store8:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - local_net
volumes:
  mysql_store8:
    external: true
networks:
  local_net:
    external: true
